name: Cargo Audit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 3"
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  cargo-audit:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: stable

      - name: Run cargo-audit
        uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
